image: maven:3.3.9-jdk-8

pipelines:
  default:
    - step:
        script:
          - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR